package com.nineton.guoguo.utils;

public enum JsonTarget{
	HOT_ITEM_LIST,
	TMALL_SOECIAL_LIST,
	RANDOM_ITEM_LIST,
	SPECIAL_TOPIC_LIST,
	TOPIC_ITEMS_LIST,
	ITEM_DETAIL,
	CLASSIFY_LIST,
	HOT_KEYWORD_LIST,
	SEARCHED_ITEM_LIST,
	VOID_OPERATION
}
